apiVersion: v1
kind: Namespace
metadata:
  name: node-remediation
spec: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sciuro
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sciuro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sciuro
subjects:
- kind: ServiceAccount
  name: sciuro
  namespace: node-remediation

