version: '2'
services:
  web:
    labels:
      - "docker.group=efk"
    image: httpd
    container_name: httpd
    ports:
      - "32030:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    labels:
      - "docker.group=efk"
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    labels:
      - "docker.group=efk"
    image: karstensiemer/elasticsearch-arm:6.2.4
    container_name: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    labels:
      - "docker.group=efk"
    image: armhfbuild/kibana:4
    container_name: kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"