ac_off:
  alias: AC Off
  sequence:
  - service: shell_command.ac_off
    data: {}
  - condition: state
    entity_id: script.ac_off
    state: 'on'
  mode: single
ubuntu_off:
  alias: Ubuntu Off
  sequence:
  - service: shell_command.ubuntu_off
    data: {}
  mode: single
centos_save:
  alias: Save Centos
  sequence:
  - service: shell_command.centos_save
    data: {}
  mode: single
ac_hot_28:
  alias: AC HOT 28
  sequence:
  - service: shell_command.ac_hot_28
    data: {}
  - condition: state
    entity_id: script.ac_hot_28
    state: 'on'
  mode: single
light_switch:
  alias: Light Switch
  sequence:
  - service: shell_command.light_switch
    data: {}
  mode: single
light_dim_down:
  alias: Light Dim Down
  sequence:
  - service: shell_command.light_dim_down
    data: {}
  mode: single
light_dim_up:
  alias: Light Dim Up
  sequence:
  - service: shell_command.light_dim_up
    data: {}
  mode: single
garmin_type_sync:
  alias: Garmin Activity Type Corrector
  sequence:
  - service: shell_command.garmin_type_sync
    data: {}
  mode: single
tv_switch:
  alias: TV Switch
  sequence:
  - service: shell_command.tv_switch
    data: {}
  mode: single
tv_source:
  alias: TV Source Button
  sequence:
  - service: shell_command.tv_source
    data: {}
  mode: single
tv_left:
  alias: TV Left Button
  sequence:
  - service: shell_command.tv_left
    data: {}
  mode: single
tv_right:
  alias: TV Right Button
  sequence:
  - service: shell_command.tv_right
    data: {}
  mode: single
tv_up:
  alias: TV Up Button
  sequence:
  - service: shell_command.tv_up
    data: {}
  mode: single
tv_down:
  alias: TV Down Button
  sequence:
  - service: shell_command.tv_down
    data: {}
  mode: single
tv_ok:
  alias: TV Ok Button
  sequence:
  - service: shell_command.tv_ok
    data: {}
  mode: single
tv_ok:
  alias: TV Ok Button
  sequence:
  - service: shell_command.tv_ok
    data: {}
  mode: single
tv_vol_up:
  alias: TV Volume Up
  sequence:
  - service: shell_command.tv_vol_up
    data: {}
  mode: single
tv_vol_down:
  alias: TV Volume Down
  sequence:
  - service: shell_command.tv_vol_down
    data: {}
  mode: single
