version: '2'
services:
  keycloak:
    labels:
      - "docker.group=keycloak"
    image: ruifigueiredo/rpi-keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
#      - "9990"

networks:
  default:
    external:
      name: iotstack_default
